"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Bird Cabrera and <FULL NAME>, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ac82885
UT EID 2: N/A
"""

def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).
 
	pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
           in s that contains no repeating characters.
    """
    max_length = 0
    for i in range(len(s)):
        used_characters = []
        for j in range(i, len(s)):
            if s[j] in used_characters:
                break
            used_characters.append(s[j])
            max_length = max(max_length, len(used_characters))
    return max_length

def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_len =0
    for i in range(len(s)):
        length = 0
        dict = {}
        for j in range(i,len(s)):
            chara = s[j]
            if chara in dict and dict[chara] >0:
                break
            dict[chara]=1
            length+=1
            if length > max_len:
                max_len = length
    return max_len

def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    char_index = {}
    max_len = 0
    l = 0
    
    for r, char in enumerate(s):
        if char in char_index and char_index[char] >= l:
            l = char_index[char] + 1
        char_index[char] = r
        length = r - l + 1
        if length > max_len:
            max_len = length
    return max_len
